### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kevdogg** [damsonn/hue-state#2]
Thanks for the script -- Nice work

I played for a few hours with the script on a MacOSX and Ubuntu host
I only played with the docker image on Ubuntu

For both hosts, I had to modify your main.js script to include bri, hue and sat in order for your script to reset the light values.  With this simple command the script would work if ran using node command as well as forever. 

In terms of the docker image, since the source was downloaded directly, it didn't work.  

I'm having a hard time figuring out where your script logs.  I ran the script with > main.log 2> error.log to get the output.   I have no idea how to do this with the docker image.

**Comment by damsonn** [comment]
Hi Kev,

thanks for taking the time to report this!

Would you mind sharing your modifications ? ( on this issue or by creating a PR ideally )

you need to run `docker build -t hue-state .` from the repo, so it will fetch the source locally.

Regarding the logs, docker capture the main process std output. to check the logs, just run `docker logs containerName` more info -> https://docs.docker.com/engine/reference/commandline/logs/

**Comment by kevdogg** [comment]
Thanks for getting back to me.  I'm really learning a lot about nodejs and docker containers.  Both just a little foreign for me.  Below are my modification to main.js

Issues still unresolved
1. When the script works -- it takes anywhere from 10 sec to sometimes up to 2 min to work.  So there is definitely a latency issue.  I'm not sure if the delay is due to receiving the information or trying to reset the lights.   When I type the commands manually within the debug clipboard I'm not seeing much latency.  I'll probably have to modify the script in order to collect more logs in terms of timing of such events.  Another possibility would be to send the change code repeatedly for like three separate times or possibly more similar to how a TV remote works which often has to send the same code repeatedly or in a burst.

Also for some reason the script is confusing the lights, meaning its got the order all wrong.  It's sending the wrong color to the wrong bulb.  Seemingly for whatever reason when I check the status of the bulbs on the script page the names associated with each bulb are correct, but the numbering 1,2,3 etc has been re-ordered.  Perhaps the scipt could send by light name rather than number -- however I'm not sure if this is part of the api. If not you'd have to store the number, name and do a lookup when the power is back on.  

#!/usr/bin/env node
"use strict";
const _ = require('lodash');
const util = require('util');
const rest = require('restler');
const argv = require('optimist')
        .default('interval', 2000)
        .usage('Store your hue lights state and restore them after power off\nUsage: $0 --host [string] --username [string]')
        .demand(['host','username'])
        .argv;

let baseUrl = `http://${argv.host}/api/${argv.username}`
let prevStates = {};

function resetLamp(lampName, state) {
  util.log(`going to reset lamp ${lampName}`);
  // only pick the brigthness and hue if present in state
  let updatePayload = _.pick(state, ['bri', 'hue', 'sat']);
  util.log(updatePayload);
  rest.putJson(`${baseUrl}/lights/${lampName}/state`, updatePayload).on('complete', (data, response) => {
    // TODO handle failure
  });
};

function checkStates() {
  rest.get(baseUrl + '/lights').on('complete', result => {
    if (result instanceof Error) {
      util.log('Error:', result.message);
    } else {
      let states = _.mapValues(result, v => v.state);
      // detect a newly reachable lamp
      _.each(states, (state, lampName) => {
        if (state.reachable && prevStates[lampName] && !prevStates[lampName].reachable) {
          resetLamp(lampName, prevStates[lampName]);
        }
      });
      // replace prev states with current
      prevStates = states;
    }
  });
};

util.log('started hue state deamon');
setInterval(checkStates, argv.interval);

You've given me a start, however and I thank you.

**Comment by damsonn** [comment]
Hi Kev, a couple of things :
- about latency, I had somewhere between 2-10sec ... It's due to a lag between the moment you turn on the power and the moment the light is picked up by the bridge. AFIK nothing we can do about that. But 2 mins seems huge, yeah add some logs, it should help.
- regarding the issue with light number, maybe you need to update your bridge firmware **OR** the API has changed and I haven't updated the code ... I don't have access to my hue lights for a few weeks ... so I can't help right now. But let me know if you are stuck.
- the api docs for hue is quite good, you need to signup to view it I think http://www.developers.meethue.com/documentation/lights-api

good luck ;-)
